spring.application.name=eventhub-api
spring.profiles.active=dev

app.name=EventHub
app.version=1.0.0

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null